-- Analiza miesięczna paczkomatu

BEGIN    
    P_RAPORT_MIESIAC_PACZKOMAT('WAW01', TRUNC(SYSDATE, 'MM'));
END;
/

SELECT 
    DROP_POINT_ID,
    TOTAL_NADAN,
    TOTAL_ODBIOROW,
    SR_CZAS_W_SKRYTCE_H,
    SR_PROCENT_TERMINOWYCH,
    SR_OCENA_KLIENTOW,
    TOTAL_KOSZT_OBSLUGI,
    TOTAL_AWARII
FROM V_DASHBOARD_PACZKOMATY
ORDER BY SR_OCENA_KLIENTOW DESC;

SELECT 
    TO_CHAR(DATA_ANALIZY, 'YYYY-MM-DD') AS DATA,
    LICZBA_NADAN,
    LICZBA_ODBIOROW,
    SREDNI_CZAS_W_SKRYTCE_H,
    PROCENT_TERMINOWYCH_ODBIOROW,
    OCENA_KLIENTOW
FROM STATYSTYKI_PUNKTOW_ODBIORU
WHERE DROP_POINT_ID = 'WAW01'
    AND DATA_ANALIZY >= TRUNC(SYSDATE) - 7
ORDER BY DATA_ANALIZY DESC;