--  Kontrola budżetowa

SELECT 
    KATEGORIA_KOSZTOW,
    MIESIAC,
    KWOTA_PLAN,
    KWOTA_RZECZYWISTA,
    ROZNICA,
    PROCENT_ROZNICA
FROM V_ANALIZA_KOSZTOW
WHERE PROCENT_ROZNICA > 5
    AND MIESIAC >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -3)
ORDER BY PROCENT_ROZNICA DESC;

SELECT 
    MIESIAC,
    KWOTA_PLAN,
    KWOTA_RZECZYWISTA,
    PROCENT_ROZNICA,
    SUMA_NARASTAJACO
FROM V_ANALIZA_KOSZTOW
WHERE KATEGORIA_KOSZTOW = 'PALIWO'
    AND MIESIAC >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6)
ORDER BY MIESIAC;
