
-- Analiza wydajności sortowni

SELECT 
    SORTOWNIA_ID,
    OKRES_ROZLICZENIOWY,
    LICZBA_PRACOWNIKOW,
    TOTAL_PACZEK,
    SR_PACZEK_NA_GODZ,
    SR_WSKAZNIK_WYDAJNOSCI,
    ROUND(TOTAL_USZKODZEN * 1000.0 / NULLIF(TOTAL_PACZEK, 0), 2) AS USZKODZENIA_NA_1000,
    ROUND(TOTAL_ZGUBIEN * 1000.0 / NULLIF(TOTAL_PACZEK, 0), 2) AS ZGUBIENIA_NA_1000
FROM V_WYDAJNOSC_SORTOWNI
WHERE OKRES_ROZLICZENIOWY = TO_CHAR(SYSDATE, 'YYYY-MM')
ORDER BY SR_WSKAZNIK_WYDAJNOSCI DESC;