-- Analiza transakcji i przychodów

SELECT 
    DATA_TRANSAKCJI,
    TYP_TRANSAKCJI,
    LICZBA_TRANSAKCJI,
    PRZYCHOD_BRUTTO,
    SR_CZAS_DOSTAWY_H,
    PROCENT_W_TERMINIE
FROM V_PODSUMOWANIE_TRANSAKCJI
WHERE DATA_TRANSAKCJI >= TRUNC(SYSDATE) - 7
ORDER BY DATA_TRANSAKCJI DESC, TYP_TRANSAKCJI;

SELECT 
    DATA_TRANSAKCJI,
    SUM(PRZYCHOD_BRUTTO) AS PRZYCHOD_DZIENNY,
    SUM(LICZBA_TRANSAKCJI) AS TRANSAKCJE_DZIENNE,
    ROUND(AVG(PROCENT_W_TERMINIE), 2) AS SR_PROCENT_TERMINOWYCH
FROM V_PODSUMOWANIE_TRANSAKCJI
GROUP BY DATA_TRANSAKCJI
ORDER BY DATA_TRANSAKCJI DESC;