-- SCENARIUSZ 6: Przegląd kadrowy

SELECT * FROM (
    SELECT 
        TYP_PRACOWNIKA,
        PRACOWNIK_ID,
        OCENA_WYDAJNOSC,
        OCENA_SLOWNA,
        REKOMENDACJA_PODWYZKA,
        RANKING_W_GRUPIE
    FROM V_OCENY_PRACOWNIKOW
    WHERE TYP_PRACOWNIKA = 'KURIER'
        AND OKRES_OCENY = TO_CHAR(SYSDATE, 'YYYY')
    ORDER BY OCENA_WYDAJNOSC DESC
) WHERE ROWNUM <= 5;

SELECT 
    TYP_PRACOWNIKA,
    COUNT(*) AS LICZBA,
    AVG(REKOMENDACJA_PODWYZKA) AS SR_PODWYZKA,
    SUM(REKOMENDACJA_PODWYZKA) AS SUMA_PODWYZEK
FROM V_OCENY_PRACOWNIKOW
WHERE OKRES_OCENY = TO_CHAR(SYSDATE, 'YYYY')
    AND REKOMENDACJA_PODWYZKA > 0
GROUP BY TYP_PRACOWNIKA;