EXEC P_ANALIZA_WYDAJNOSCI_KURIERA(1, TO_CHAR(SYSDATE, 'YYYY-MM'));

EXEC P_RAPORT_MIESIAC_PACZKOMAT('WAW01', TRUNC(SYSDATE, 'MM'));

EXEC P_OCENA_PRACOWNIKA('KURIER', 1, TO_CHAR(SYSDATE, 'YYYY'), 1);

SELECT * FROM (
    SELECT * FROM V_RANKING_KURIEROW
    WHERE OKRES_ROZLICZENIOWY = TO_CHAR(SYSDATE, 'YYYY-MM')
    ORDER BY RANKING
) WHERE ROWNUM <= 5;


SELECT * FROM V_DASHBOARD_PACZKOMATY
ORDER BY SR_OCENA_KLIENTOW DESC;

SELECT * FROM V_ANALIZA_KOSZTOW
WHERE PROCENT_ROZNICA > 5
ORDER BY MIESIAC DESC, PROCENT_ROZNICA DESC;

COMMIT;


-- 1. Analiza sezonowości - wpływ dni tygodnia na operacje
SELECT 
    dc.NAZWA_DNIA,
    dc.CZY_WEEKEND,
    COUNT(DISTINCT spo.DATA_ANALIZY) AS LICZBA_DNI,
    ROUND(AVG(spo.LICZBA_NADAN), 0) AS SR_NADAN,
    ROUND(AVG(spo.LICZBA_ODBIOROW), 0) AS SR_ODBIOROW,
    ROUND(AVG(spo.SREDNI_CZAS_W_SKRYTCE_H), 2) AS SR_CZAS_SKRYTKA
FROM STATYSTYKI_PUNKTOW_ODBIORU spo
JOIN DIM_CZAS dc ON spo.DATA_ANALIZY = dc.DATA_PELNA
WHERE spo.DATA_ANALIZY >= TRUNC(SYSDATE) - 30
GROUP BY dc.NAZWA_DNIA, dc.CZY_WEEKEND, dc.DZIEN_TYGODNIA
ORDER BY dc.DZIEN_TYGODNIA;

-- 2. Wpływ świąt na operacje
SELECT 
    dc.NAZWA_SWIETA,
    COUNT(DISTINCT spo.DROP_POINT_ID) AS LICZBA_PACZKOMATOW,
    ROUND(AVG(spo.LICZBA_NADAN), 0) AS SR_NADAN,
    ROUND(AVG(spo.LICZBA_ODBIOROW), 0) AS SR_ODBIOROW
FROM STATYSTYKI_PUNKTOW_ODBIORU spo
JOIN DIM_CZAS dc ON spo.DATA_ANALIZY = dc.DATA_PELNA
WHERE dc.CZY_SWIETO = 'T'
    AND spo.DATA_ANALIZY >= DATE '2024-01-01'
GROUP BY dc.NAZWA_SWIETA
ORDER BY SR_NADAN DESC;

-- 3. Korelacja między oceną klientów a czasem w skrytce
SELECT 
    CASE 
        WHEN SREDNI_CZAS_W_SKRYTCE_H < 12 THEN '< 12h'
        WHEN SREDNI_CZAS_W_SKRYTCE_H < 24 THEN '12-24h'
        WHEN SREDNI_CZAS_W_SKRYTCE_H < 36 THEN '24-36h'
        ELSE '> 36h'
    END AS PRZEDZIAL_CZASU,
    COUNT(*) AS LICZBA_OBSERWACJI,
    ROUND(AVG(OCENA_KLIENTOW), 2) AS SR_OCENA,
    ROUND(AVG(PROCENT_TERMINOWYCH_ODBIOROW), 2) AS SR_PROCENT_TERMINOWYCH
FROM STATYSTYKI_PUNKTOW_ODBIORU
WHERE DATA_ANALIZY >= TRUNC(SYSDATE) - 90
GROUP BY 
    CASE 
        WHEN SREDNI_CZAS_W_SKRYTCE_H < 12 THEN '< 12h'
        WHEN SREDNI_CZAS_W_SKRYTCE_H < 24 THEN '12-24h'
        WHEN SREDNI_CZAS_W_SKRYTCE_H < 36 THEN '24-36h'
        ELSE '> 36h'
    END
ORDER BY 1;