DROP TABLE FAKT_TRANSAKCJE CASCADE CONSTRAINTS;
DROP TABLE DIM_CZAS CASCADE CONSTRAINTS;
DROP TABLE ANALIZA_ZWROTOW CASCADE CONSTRAINTS;
DROP TABLE KOSZTY_OPERACYJNE CASCADE CONSTRAINTS;
DROP TABLE OCENY_PRACOWNIKOW CASCADE CONSTRAINTS;
DROP TABLE WYDAJNOSC_PRACOWNIKOW_SORTOWNI CASCADE CONSTRAINTS;
DROP TABLE WYDAJNOSC_KURIEROW CASCADE CONSTRAINTS;
DROP TABLE STATYSTYKI_PUNKTOW_ODBIORU CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_STAT_PUNKTOW;
DROP SEQUENCE SEQ_WYDAJNOSC;
DROP SEQUENCE SEQ_PROGNOZY;
DROP SEQUENCE SEQ_RENTOWNOSC;
DROP SEQUENCE SEQ_OPTYMALIZACJA;
DROP SEQUENCE SEQ_WSKAZNIKI;
DROP SEQUENCE SEQ_OCENY;