DROP TABLE STAT_AGREGACJE_MIESIECZNE;
DROP TABLE STAT_BLEDY_AWARIE_SNAPSHOT;
DROP TABLE STAT_DROPPOINTY_SNAPSHOT;
DROP TABLE STAT_PRZESYLKI_SNAPSHOT;
DROP TABLE STAT_SORTOWNIE_SNAPSHOT;


SELECT * FROM STAT_AGREGACJE_MIESIECZNE;
SELECT * FROM STAT_BLEDY_AWARIE_SNAPSHOT;
SELECT * FROM STAT_DROPPOINTY_SNAPSHOT;
SELECT * FROM STAT_PRZESYLKI_SNAPSHOT;
SELECT * FROM STAT_KURIERZY_SNAPSHOT;
SELECT * FROM STAT_SORTOWNIE_SNAPSHOT;