CREATE TABLE STAT_SORTOWNIE_SNAPSHOT (
    SortowniaID                 NUMBER        NOT NULL,
    SortowniaNazwa              VARCHAR2(100),
    Miasto                      VARCHAR2(50),
    Wojewodztwo                 VARCHAR2(50),
    LiczbaPrzetworzonych        NUMBER,
    LiczbaPracownikow           NUMBER,
    LiczbaKurierow              NUMBER,
    LiczbaObslugiwanychDroppointow NUMBER,
    SredniCzasPrzetwarzaniaMinuty NUMBER,
    LiczbaOperacjiSortowania    NUMBER,
    LiczbaOperacjiZaladunku     NUMBER,
    LiczbaOperacjiRozladunku    NUMBER,
    DataAktualizacji            TIMESTAMP
)
PARTITION BY RANGE (DataAktualizacji)
INTERVAL (NUMTODSINTERVAL(1, 'MONTH'))
(
  PARTITION p_start VALUES LESS THAN (DATE '2024-01-01')
);

CREATE TABLE STAT_PRZESYLKI_SNAPSHOT (
    DataDostawy                 DATE,
    Gabaryt                     CHAR(1),
    WojewodztwoNadania          VARCHAR2(50),
    WojewodztwoOdbioru          VARCHAR2(50),
    LiczbaPrzesylek             NUMBER,
    SredniCzasTransportuGodziny NUMBER,
    LiczbaDoDroppointow         NUMBER,
    LiczbaDoAdresow             NUMBER,
    LiczbaZwrotow               NUMBER,
    DataAktualizacji            TIMESTAMP
)
PARTITION BY RANGE (DataAktualizacji)
INTERVAL (NUMTODSINTERVAL(1, 'MONTH'))
(
  PARTITION p_start VALUES LESS THAN (DATE '2024-01-01')
);

CREATE TABLE STAT_DROPPOINTY_SNAPSHOT (
    DroppointID                 NUMBER        NOT NULL,
    DroppointNazwa              VARCHAR2(100),
    Typ                         VARCHAR2(20),
    Miasto                      VARCHAR2(50),
    Wojewodztwo                 VARCHAR2(50),
    SortowniaID                 NUMBER,
    LiczbaSkrytek               NUMBER,
    LiczbaWolnychSkrytek        NUMBER,
    LiczbaZajetychSkrytek       NUMBER,
    LiczbaObsluzonychPrzesylek  NUMBER,
    LiczbaAwarii                NUMBER,
    LiczbaOtwartychAwarii       NUMBER,
    ProcentWykorzystania        NUMBER(5,2),
    DataAktualizacji            TIMESTAMP
)
PARTITION BY RANGE (DataAktualizacji)
INTERVAL (NUMTODSINTERVAL(1, 'MONTH'))
(
  PARTITION p_start VALUES LESS THAN (DATE '2024-01-01')
);

CREATE TABLE STAT_BLEDY_AWARIE_SNAPSHOT (
    DataZgloszenia              DATE,
    KodBledu                    VARCHAR2(10),
    Kategoria                   VARCHAR2(50),
    PoziomWaznosci              VARCHAR2(20),
    ZrodloZgloszenia            VARCHAR2(20),
    LiczbaZgloszen              NUMBER,
    LiczbaPotwierdzonych        NUMBER,
    LiczbaAwarii                NUMBER,
    LiczbaNaprawionych          NUMBER,
    SredniCzasNaprawyGodziny    NUMBER,
    DataAktualizacji            TIMESTAMP
)
PARTITION BY RANGE (DataAktualizacji)
INTERVAL (NUMTODSINTERVAL(1, 'MONTH'))
(
  PARTITION p_start VALUES LESS THAN (DATE '2024-01-01')
);

CREATE TABLE STAT_AGREGACJE_MIESIECZNE (
    Rok                         NUMBER,
    Miesiac                     NUMBER,
    LiczbaPrzesylek             NUMBER,
    AktywniKurierzy             NUMBER,
    AktywneSortownie            NUMBER,
    AktywneDroppointy           NUMBER,
    SredniCzasDostawyGodziny    NUMBER,
    PrzesylkiGabarytA           NUMBER,
    PrzesylkiGabarytB           NUMBER,
    PrzesylkiGabarytC           NUMBER,
    DataAktualizacji            TIMESTAMP
)
PARTITION BY RANGE (DataAktualizacji)
INTERVAL (NUMTODSINTERVAL(1, 'MONTH'))
(
  PARTITION p_start VALUES LESS THAN (DATE '2024-01-01')
);

CREATE TABLE STAT_KURIERZY_SNAPSHOT (
    KurierID                      NUMBER         NOT NULL,
    Imie                          VARCHAR2(50),
    Nazwisko                      VARCHAR2(100),
    Wojewodztwo                   VARCHAR2(50),
    SortowniaID                   NUMBER,
    SortowniaNazwa                VARCHAR2(100),
    LiczbaDostarczonychPrzesylek  NUMBER,
    LiczbaUdanychDostaw           NUMBER,
    LiczbaNieudanychDostaw        NUMBER,
    SredniCzasDostawyMinuty       NUMBER,
    PierwszaOperacja              TIMESTAMP,
    OstatniaOperacja              TIMESTAMP,
    DataAktualizacji              TIMESTAMP
)
PARTITION BY RANGE (DataAktualizacji)
INTERVAL (NUMTODSINTERVAL(1, 'MONTH'))
(
  PARTITION p_start VALUES LESS THAN (DATE '2024-01-01')
);



CREATE TABLE D_CZAS (
    DATA_ID DATE PRIMARY KEY,
    ROK NUMBER(4),
    KWARTAL NUMBER(1),
    MIESIAC NUMBER(2),
    TYDZIEN NUMBER(2),
    DZIEN_MIESIACA NUMBER(2),
    DZIEN_TYGODNIA NUMBER(1),
    NAZWA_MIESIACA VARCHAR2(20),
    NAZWA_DNIA VARCHAR2(20),
    CZY_WEEKEND CHAR(1),
    CZY_SWIETO CHAR(1)
);

CREATE TABLE D_GEOGRAFIA (
    GEOGRAFIA_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    WOJEWODZTWO VARCHAR2(50) NOT NULL,
    REGION VARCHAR2(50),
    STREFA_DOSTAWY VARCHAR2(20)
);

CREATE TABLE ETL_HISTORIA_LADOWANIA (
    LADOWANIE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAZWA_PROCESU VARCHAR2(100),
    DATA_ROZPOCZECIA TIMESTAMP,
    DATA_ZAKONCZENIA TIMESTAMP,
    LICZBA_WIERSZY_WSTAWIONYCH NUMBER(10),
    LICZBA_WIERSZY_ZAKTUALIZOWANYCH NUMBER(10),
    LICZBA_WIERSZY_BLEDNYCH NUMBER(10),
    STATUS VARCHAR2(20),
    KOMUNIKAT_BLEDU VARCHAR2(4000),
    CZAS_WYKONANIA_SEKUNDY NUMBER(10)
);

CREATE TABLE D_KURIER_PROFIL (
    KURIER_ID NUMBER(10) PRIMARY KEY,
    IMIE VARCHAR2(50),
    NAZWISKO VARCHAR2(100),
    SORTOWNIA_ID NUMBER(10),
    WOJEWODZTWO VARCHAR2(50),
    DATA_ZATRUDNIENIA DATE,
    SREDNIA_DZIENNA_DOSTAW NUMBER(10,2),
    MAX_DZIENNA_DOSTAW NUMBER(10),
    SKUTECZNOSC_PROCENT NUMBER(5,2),
    SREDNI_CZAS_DOSTAWY NUMBER(10,2),
    MAX_DOPUSZCZALNE_DOSTAW NUMBER(10) DEFAULT 50,
    PREFEROWANY_GABARYT CHAR(1),
    OSTATNIA_AKTUALIZACJA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE F_KURIER_BIEZACE_OBLOZENIE (
    DATA_SNAPSHOT DATE NOT NULL,
    KURIER_ID NUMBER(10) NOT NULL,
    SORTOWNIA_ID NUMBER(10),
    LICZBA_PRZYPISANYCH NUMBER(10) DEFAULT 0,
    LICZBA_W_DOSTAWIE NUMBER(10) DEFAULT 0,
    LICZBA_OCZEKUJACYCH NUMBER(10) DEFAULT 0,
    LICZBA_GABARYT_A NUMBER(10) DEFAULT 0,
    LICZBA_GABARYT_B NUMBER(10) DEFAULT 0,
    LICZBA_GABARYT_C NUMBER(10) DEFAULT 0,
    PRZEWIDYWANY_CZAS_REALIZACJI_H NUMBER(10,2),
    PROCENT_OBLOZENIA NUMBER(5,2),
    WOLNA_POJEMNOSC NUMBER(10),
    DATA_AKTUALIZACJI TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_F_BIEZACE_OBLOZENIE PRIMARY KEY (DATA_SNAPSHOT, KURIER_ID)
);

CREATE TABLE D_WZORCE_CZASOWE (
    DZIEN_TYGODNIA NUMBER(1) NOT NULL,
    GODZINA NUMBER(2) NOT NULL,
    WOJEWODZTWO VARCHAR2(50) NOT NULL,
    WSPOLCZYNNIK_OBLOZENIA NUMBER(5,2) DEFAULT 1.0,
    SREDNI_CZAS_DOSTAWY_DODATKOWY NUMBER(10) DEFAULT 0,
    LICZBA_OBSERWACJI NUMBER(10),
    OSTATNIA_AKTUALIZACJA DATE,
    CONSTRAINT PK_D_WZORCE PRIMARY KEY (DZIEN_TYGODNIA, GODZINA, WOJEWODZTWO)
);
