SET SERVEROUTPUT ON;
SET ECHO ON;

-- Sekwencje


CREATE SEQUENCE SEQ_STAT_PUNKTOW START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_WYDAJNOSC START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROGNOZY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RENTOWNOSC START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_OPTYMALIZACJA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_WSKAZNIKI START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_OCENY START WITH 1 INCREMENT BY 1;


-- Tabele Statystyczne 

CREATE TABLE STATYSTYKI_PUNKTOW_ODBIORU (
    STAT_ID NUMBER PRIMARY KEY,
    DROP_POINT_ID VARCHAR2(10) NOT NULL,
    DATA_ANALIZY DATE NOT NULL,
    LICZBA_NADAN NUMBER DEFAULT 0,
    LICZBA_ODBIOROW NUMBER DEFAULT 0,
    LICZBA_ZWROTOW NUMBER DEFAULT 0,
    LICZBA_NIEODEBRANYCH NUMBER DEFAULT 0,
    CZAS_W_SKRYTCE_H NUMBER(6,2),
    SREDNI_CZAS_W_SKRYTCE_H NUMBER(6,2),
    PROCENT_TERMINOWYCH_ODBIOROW NUMBER(5,2),
    KOSZT_OBSLUGI NUMBER(10,2),
    LICZBA_AWARII NUMBER DEFAULT 0,
    OCENA_KLIENTOW NUMBER(3,2),
    DATA_UTWORZENIA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_STAT_PUNKT_DATA UNIQUE (DROP_POINT_ID, DATA_ANALIZY)
) TABLESPACE RBD_DATA;

CREATE INDEX IDX_STAT_DATA ON STATYSTYKI_PUNKTOW_ODBIORU(DATA_ANALIZY) TABLESPACE RBD_INDEX;
CREATE INDEX IDX_STAT_PUNKT ON STATYSTYKI_PUNKTOW_ODBIORU(DROP_POINT_ID) TABLESPACE RBD_INDEX;


CREATE TABLE WYDAJNOSC_KURIEROW (
    WYDAJNOSC_ID NUMBER PRIMARY KEY,
    KURIER_ID NUMBER NOT NULL,
    DATA_ANALIZY DATE NOT NULL,
    OKRES_ROZLICZENIOWY VARCHAR2(7), -- YYYY-MM
    LICZBA_DNI_PRACY NUMBER,
    LICZBA_DOSTAW NUMBER,
    LICZBA_ODBIOROW NUMBER,
    LICZBA_ZWROTOW NUMBER,
    SREDNI_CZAS_DOSTAWY_MIN NUMBER(6,2),
    NAJKROTSZY_CZAS_MIN NUMBER,
    NAJDLUZSZY_CZAS_MIN NUMBER,
    CZAS_PRACY_LACZNIE_H NUMBER(8,2),
    SREDNI_CZAS_NA_PRZESYLKE_MIN NUMBER(6,2),
    KOSZT_KURIERA NUMBER(10,2),
    LICZBA_USZKODZEN NUMBER DEFAULT 0,
    LICZBA_ZGUBIEN NUMBER DEFAULT 0,
    WSKAZNIK_WYDAJNOSCI NUMBER(6,2), -- 100 = średnia
    DATA_UTWORZENIA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_WYD_KURIER_OKRES UNIQUE (KURIER_ID, OKRES_ROZLICZENIOWY)
) TABLESPACE RBD_DATA;

CREATE INDEX IDX_WYD_KURIER ON WYDAJNOSC_KURIEROW(KURIER_ID) TABLESPACE RBD_INDEX;
CREATE INDEX IDX_WYD_OKRES ON WYDAJNOSC_KURIEROW(OKRES_ROZLICZENIOWY) TABLESPACE RBD_INDEX;


CREATE TABLE WYDAJNOSC_PRACOWNIKOW_SORTOWNI (
    WYDAJNOSC_ID NUMBER PRIMARY KEY,
    PRACOWNIK_ID NUMBER NOT NULL,
    SORTOWNIA_ID VARCHAR2(10) NOT NULL,
    DATA_ANALIZY DATE NOT NULL,
    OKRES_ROZLICZENIOWY VARCHAR2(7), -- YYYY-MM
    LICZBA_DNI_PRACY NUMBER,
    LICZBA_ZMIAN NUMBER,
    LICZBA_GODZIN_LACZNIE NUMBER(8,2),
    LICZBA_PACZEK NUMBER,
    SREDNIA_PACZEK_NA_GODZINE NUMBER(8,2),
    WSKAZNIK_WYDAJNOSCI NUMBER(6,2), -- 100 = średnia dla sortowni
    LICZBA_USZKODZEN NUMBER DEFAULT 0,
    LICZBA_ZGUBIEN NUMBER DEFAULT 0,
    OCENA_KIEROWNIKA NUMBER(3,2),
    DATA_UTWORZENIA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_WYD_PRAC_OKRES UNIQUE (PRACOWNIK_ID, OKRES_ROZLICZENIOWY)
) TABLESPACE RBD_DATA;

CREATE INDEX IDX_WYD_PRAC ON WYDAJNOSC_PRACOWNIKOW_SORTOWNI(PRACOWNIK_ID) TABLESPACE RBD_INDEX;
CREATE INDEX IDX_WYD_SORT ON WYDAJNOSC_PRACOWNIKOW_SORTOWNI(SORTOWNIA_ID) TABLESPACE RBD_INDEX;

CREATE TABLE OCENY_PRACOWNIKOW (
    OCENA_ID NUMBER PRIMARY KEY,
    TYP_PRACOWNIKA VARCHAR2(30), -- KURIER, SORTOWNIA, OBSLUGA
    PRACOWNIK_ID NUMBER NOT NULL,
    OKRES_OCENY VARCHAR2(10), -- 2025-Q1, 2025-H1, 2025
    DATA_OCENY DATE,
    OCENA_WYDAJNOSC NUMBER(3,2), -- 1-5
    OCENA_SLOWNA VARCHAR2(50), -- WYBITNY, BARDZO_DOBRY, DOBRY, DOSTATECZNY, NIEDOSTATECZNY
    REKOMENDACJA_AWANS CHAR(1) DEFAULT 'N',
    REKOMENDACJA_PODWYZKA NUMBER(5,2),
    REKOMENDACJA_PREMIA NUMBER(5,2),
    KOMENTARZ_KIEROWNIKA CLOB DEFAULT NULL,
    KOMENTARZ_HR CLOB DEFAULT NULL,
    CELE_NA_NASTEPNY_OKRES CLOB DEFAULT NULL,
    OCENIAJACY_ID INTEGER, -- ID osoby oceniającej
    DATA_UTWORZENIA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS_OCENY VARCHAR2(30) DEFAULT 'WSTEPNA'
) TABLESPACE RBD_DATA;

CREATE INDEX IDX_OCENA_PRAC ON OCENY_PRACOWNIKOW(PRACOWNIK_ID) TABLESPACE RBD_INDEX;
CREATE INDEX IDX_OCENA_OKRES ON OCENY_PRACOWNIKOW(OKRES_OCENY) TABLESPACE RBD_INDEX;

CREATE TABLE KOSZTY_OPERACYJNE (
    KOSZT_ID NUMBER PRIMARY KEY,
    MIESIAC DATE NOT NULL,
    KATEGORIA_KOSZTOW VARCHAR2(50),
    KWOTA_PLAN NUMBER(12,2),
    KWOTA_RZECZYWISTA NUMBER(12,2),
    ROZNICA NUMBER(12,2),
    DATA_KSIEGOWANIA DATE,
    WPROWADZONE_PRZEZ VARCHAR2(100)
) TABLESPACE RBD_DATA;

CREATE INDEX IDX_KOSZT_MIESIAC ON KOSZTY_OPERACYJNE(MIESIAC) TABLESPACE RBD_INDEX;
CREATE INDEX IDX_KOSZT_KAT ON KOSZTY_OPERACYJNE(KATEGORIA_KOSZTOW) TABLESPACE RBD_INDEX;

CREATE TABLE ANALIZA_ZWROTOW (
    ANALIZA_ID NUMBER PRIMARY KEY,
    MIESIAC DATE NOT NULL,
    LICZBA_ZWROTOW_OGOLEM NUMBER,
    LICZBA_ZWROTOW_NIEODEBRANE NUMBER,
    LICZBA_ZWROTOW_USZKODZONE NUMBER,
    LICZBA_ZWROTOW_BLEDNY_ADRES NUMBER,
    LICZBA_ZWROTOW_INNE NUMBER,
    PROCENT_NIEODEBRANE NUMBER(5,2),
    PROCENT_USZKODZONE NUMBER(5,2),
    PROCENT_BLEDNY_ADRES NUMBER(5,2),
    DATA_ANALIZY TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE RBD_DATA;

CREATE INDEX IDX_ZWROT_MIESIAC ON ANALIZA_ZWROTOW(MIESIAC) TABLESPACE RBD_INDEX;

CREATE TABLE DIM_CZAS (
    DATA_ID NUMBER PRIMARY KEY,
    DATA_PELNA DATE UNIQUE NOT NULL,
    ROK NUMBER(4),
    MIESIAC NUMBER(2),
    DZIEN NUMBER(2),
    KWARTAL NUMBER(1),
    TYDZIEN_ROKU NUMBER(2),
    DZIEN_TYGODNIA NUMBER(1),
    NAZWA_MIESIACA VARCHAR2(20),
    NAZWA_DNIA VARCHAR2(20),
    CZY_WEEKEND CHAR(1),
    CZY_SWIETO CHAR(1),
    NAZWA_SWIETA VARCHAR2(100)
) TABLESPACE RBD_DATA;

CREATE INDEX IDX_DIM_DATA ON DIM_CZAS(DATA_PELNA) TABLESPACE RBD_INDEX;
CREATE INDEX IDX_DIM_ROK_MIESIAC ON DIM_CZAS(ROK, MIESIAC) TABLESPACE RBD_INDEX;


CREATE TABLE FAKT_TRANSAKCJE (
    TRANSAKCJA_ID NUMBER PRIMARY KEY,
    DATA_TRANSAKCJI DATE NOT NULL,
    PRZESYLKA_ID NUMBER,
    KLIENT_NADAWCA_ID NUMBER,
    KLIENT_ODBIORCA_ID NUMBER,
    TYP_TRANSAKCJI VARCHAR2(30), -- NADANIE, ODBIOR, ZWROT
    PACZKOMAT_NADANIA_ID VARCHAR2(10),
    PACZKOMAT_ODBIORU_ID VARCHAR2(10),
    KURIER_ID NUMBER,
    GABARYT CHAR(1),
    WAGA_KG NUMBER(8,3),
    KWOTA_POBRANIA NUMBER(10,2),
    CENA_NETTO NUMBER(8,2),
    CENA_BRUTTO NUMBER(8,2),
    CZAS_DOSTAWY_H NUMBER(6,2),
    CZAS_W_SYSTEMIE_H NUMBER(8,2),
    CZY_DOSTARCZONA CHAR(1),
    CZY_W_TERMINIE CHAR(1),
    CZY_REKLAMACJA CHAR(1) DEFAULT 'N'
) PARTITION BY RANGE (DATA_TRANSAKCJI) 
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION FAKT_TRANS_202501 VALUES LESS THAN (DATE '2025-02-01')
) TABLESPACE RBD_DATA;

CREATE INDEX IDX_FAKT_DATA ON FAKT_TRANSAKCJE(DATA_TRANSAKCJI) LOCAL TABLESPACE RBD_INDEX;
CREATE INDEX IDX_FAKT_NADAWCA ON FAKT_TRANSAKCJE(KLIENT_NADAWCA_ID) LOCAL TABLESPACE RBD_INDEX;
