CREATE USER admin IDENTIFIED BY admin123;

GRANT CONNECT, RESOURCE TO admin;

GRANT DBA TO admin;

GRANT CREATE USER, DROP USER, ALTER USER TO admin;
GRANT CREATE ROLE TO admin;
GRANT GRANT ANY PRIVILEGE TO admin;
GRANT GRANT ANY ROLE TO admin;

GRANT CREATE SESSION TO admin;
GRANT UNLIMITED TABLESPACE TO admin;

GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO admin;
GRANT CREATE ANY TABLE, DROP ANY TABLE TO admin;
GRANT INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE, SELECT ANY TABLE TO admin;

ALTER USER admin ACCOUNT UNLOCK;