-- Dane 
CREATE TABLESPACE RBD_DATA
    DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\rbd_data01.dbf' 
    SIZE 500M 
    AUTOEXTEND ON 
    NEXT 100M 
    MAXSIZE 5G
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

--Indeksy 

CREATE TABLESPACE RBD_INDEX
    DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\rbd_index01.dbf' 
    SIZE 200M 
    AUTOEXTEND ON 
    NEXT 50M 
    MAXSIZE 2G
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

-- Temp 

CREATE TEMPORARY TABLESPACE RBD_TEMP
    TEMPFILE 'C:\oraclexe\app\oracle\oradata\XE\rbd_temp01.dbf' 
    SIZE 100M 
    AUTOEXTEND ON 
    NEXT 50M 
    MAXSIZE 1G
    EXTENT MANAGEMENT LOCAL
    UNIFORM SIZE 1M;


CREATE USER c##RBD_ANALYTICS
    IDENTIFIED BY rbd123
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE TO c##RBD_ANALYTICS;
GRANT CREATE SESSION TO c##RBD_ANALYTICS;
GRANT CREATE TABLE TO c##RBD_ANALYTICS;
GRANT CREATE VIEW TO c##RBD_ANALYTICS;
GRANT CREATE PROCEDURE TO c##RBD_ANALYTICS;
GRANT CREATE SEQUENCE TO c##RBD_ANALYTICS;
GRANT CREATE TRIGGER TO c##RBD_ANALYTICS;
GRANT CREATE MATERIALIZED VIEW TO c##RBD_ANALYTICS;
GRANT CREATE DATABASE LINK TO c##RBD_ANALYTICS;
GRANT CREATE SYNONYM TO c##RBD_ANALYTICS;
GRANT CREATE TYPE TO c##RBD_ANALYTICS;

GRANT EXECUTE ON DBMS_LOCK TO c##RBD_ANALYTICS;
GRANT EXECUTE ON DBMS_SCHEDULER TO c##RBD_ANALYTICS;
GRANT EXECUTE ON UTL_FILE TO c##RBD_ANALYTICS;
GRANT EXECUTE ON UTL_HTTP TO c##RBD_ANALYTICS;

GRANT SELECT ANY DICTIONARY TO c##RBD_ANALYTICS;
GRANT ANALYZE ANY TO c##RBD_ANALYTICS;

CREATE ROLE c##RBD_READONLY;
GRANT CONNECT TO c##RBD_READONLY;
GRANT CREATE SESSION TO c##RBD_READONLY;


SELECT tablespace_name, 
       file_name, 
       bytes/1024/1024 AS size_mb,
       autoextensible
FROM dba_data_files
WHERE tablespace_name LIKE 'RBD%'
ORDER BY tablespace_name;


SELECT username, 
       default_tablespace, 
       temporary_tablespace,
       account_status,
       common
FROM dba_users
WHERE username LIKE 'RBD%' OR username LIKE 'C##RBD%';

SELECT * FROM dba_sys_privs WHERE grantee = 'c##RBD_ANALYTICS';
SELECT * FROM dba_role_privs WHERE grantee = 'c##RBD_ANALYTICS';