CREATE OR REPLACE VIEW V_ANALIZA_KOSZTOW AS
SELECT 
    k.MIESIAC,
    k.KATEGORIA_KOSZTOW,
    k.KWOTA_PLAN,
    k.KWOTA_RZECZYWISTA,
    k.ROZNICA,
    ROUND((k.KWOTA_RZECZYWISTA - k.KWOTA_PLAN) * 100 / NULLIF(k.KWOTA_PLAN, 0), 2) AS PROCENT_ROZNICA,
    SUM(k.KWOTA_RZECZYWISTA) OVER (PARTITION BY k.KATEGORIA_KOSZTOW ORDER BY k.MIESIAC) AS SUMA_NARASTAJACO
FROM KOSZTY_OPERACYJNE k
ORDER BY k.MIESIAC DESC, k.KATEGORIA_KOSZTOW;