CREATE OR REPLACE VIEW V_RANKING_KURIEROW AS
SELECT 
    w.KURIER_ID,
    w.OKRES_ROZLICZENIOWY,
    w.LICZBA_DOSTAW,
    w.SREDNI_CZAS_DOSTAWY_MIN,
    w.WSKAZNIK_WYDAJNOSCI,
    RANK() OVER (PARTITION BY w.OKRES_ROZLICZENIOWY ORDER BY w.WSKAZNIK_WYDAJNOSCI DESC) AS RANKING,
    CASE 
        WHEN w.WSKAZNIK_WYDAJNOSCI >= 110 THEN 'PONADPRZECIĘTNY'
        WHEN w.WSKAZNIK_WYDAJNOSCI >= 90 THEN 'PRZECIĘTNY'
        ELSE 'PONIŻEJ PRZECIĘTNEJ'
    END AS KATEGORIA
FROM WYDAJNOSC_KURIEROW w
WHERE w.OKRES_ROZLICZENIOWY >= TO_CHAR(ADD_MONTHS(SYSDATE, -3), 'YYYY-MM');
