CREATE OR REPLACE VIEW V_DASHBOARD_PACZKOMATY AS
SELECT 
    s.DROP_POINT_ID,
    COUNT(DISTINCT s.DATA_ANALIZY) AS DNI_ANALIZY,
    SUM(s.LICZBA_NADAN) AS TOTAL_NADAN,
    SUM(s.LICZBA_ODBIOROW) AS TOTAL_ODBIOROW,
    SUM(s.LICZBA_ZWROTOW) AS TOTAL_ZWROTOW,
    ROUND(AVG(s.SREDNI_CZAS_W_SKRYTCE_H), 2) AS SR_CZAS_W_SKRYTCE_H,
    ROUND(AVG(s.PROCENT_TERMINOWYCH_ODBIOROW), 2) AS SR_PROCENT_TERMINOWYCH,
    ROUND(AVG(s.OCENA_KLIENTOW), 2) AS SR_OCENA_KLIENTOW,
    SUM(s.KOSZT_OBSLUGI) AS TOTAL_KOSZT_OBSLUGI,
    SUM(s.LICZBA_AWARII) AS TOTAL_AWARII
FROM STATYSTYKI_PUNKTOW_ODBIORU s
WHERE s.DATA_ANALIZY >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -3)
GROUP BY s.DROP_POINT_ID;