CREATE OR REPLACE VIEW V_WYDAJNOSC_SORTOWNI AS
SELECT 
    w.SORTOWNIA_ID,
    w.OKRES_ROZLICZENIOWY,
    COUNT(DISTINCT w.PRACOWNIK_ID) AS LICZBA_PRACOWNIKOW,
    SUM(w.LICZBA_PACZEK) AS TOTAL_PACZEK,
    ROUND(AVG(w.SREDNIA_PACZEK_NA_GODZINE), 2) AS SR_PACZEK_NA_GODZ,
    ROUND(AVG(w.WSKAZNIK_WYDAJNOSCI), 2) AS SR_WSKAZNIK_WYDAJNOSCI,
    SUM(w.LICZBA_USZKODZEN) AS TOTAL_USZKODZEN,
    SUM(w.LICZBA_ZGUBIEN) AS TOTAL_ZGUBIEN
FROM WYDAJNOSC_PRACOWNIKOW_SORTOWNI w
WHERE w.OKRES_ROZLICZENIOWY >= TO_CHAR(ADD_MONTHS(SYSDATE, -6), 'YYYY-MM')
GROUP BY w.SORTOWNIA_ID, w.OKRES_ROZLICZENIOWY;