CREATE OR REPLACE VIEW V_PODSUMOWANIE_TRANSAKCJI AS
SELECT 
    f.DATA_TRANSAKCJI,
    f.TYP_TRANSAKCJI,
    COUNT(*) AS LICZBA_TRANSAKCJI,
    SUM(f.CENA_BRUTTO) AS PRZYCHOD_BRUTTO,
    ROUND(AVG(f.CZAS_DOSTAWY_H), 2) AS SR_CZAS_DOSTAWY_H,
    SUM(CASE WHEN f.CZY_DOSTARCZONA = 'T' THEN 1 ELSE 0 END) AS DOSTARCZONE,
    SUM(CASE WHEN f.CZY_W_TERMINIE = 'T' THEN 1 ELSE 0 END) AS W_TERMINIE,
    ROUND(SUM(CASE WHEN f.CZY_W_TERMINIE = 'T' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS PROCENT_W_TERMINIE
FROM FAKT_TRANSAKCJE f
WHERE f.DATA_TRANSAKCJI >= TRUNC(SYSDATE) - 30
GROUP BY f.DATA_TRANSAKCJI, f.TYP_TRANSAKCJI;