CREATE OR REPLACE VIEW V_OCENY_PRACOWNIKOW AS
SELECT 
    o.TYP_PRACOWNIKA,
    o.PRACOWNIK_ID,
    o.OKRES_OCENY,
    o.OCENA_WYDAJNOSC,
    o.OCENA_SLOWNA,
    o.REKOMENDACJA_PODWYZKA,
    o.STATUS_OCENY,
    RANK() OVER (PARTITION BY o.TYP_PRACOWNIKA, o.OKRES_OCENY ORDER BY o.OCENA_WYDAJNOSC DESC) AS RANKING_W_GRUPIE
FROM OCENY_PRACOWNIKOW o
WHERE o.STATUS_OCENY = 'ZATWIERDZONA';